name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      os: ubuntu-24.04
